enabled: true

replicaCount: 3
labelapp: app
group: app

genericApp:
  name: app-name

  container:
    image: add-image-here
    port: 8080

  service:
    type: ClusterIP
    protocol: TCP
    port: 8080