# Cluster IP service for backend API
apiVersion: v1
kind: Service
metadata:
  name: flask-api-cluster
  namespace: simpleapp-reactapp
  labels:
    backend: flaskapi
spec:
  selector:
    backend: flaskapi
  ports:
    - port: 5000
      targetPort: 5000

---
# Deployment for the backend API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: simpleapp-reactapp
  labels:
    backend: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      backend: flaskapi
  template:
    metadata:
      name: api-pods
      namespace: simpleapp-reactapp
      labels:
        backend: flaskapi
    spec:
      containers:
      - name: api-containers
        image: localhost:32000/simple-app-backend-api:v1
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: mongodb://root:root@mongo-cluster:27017/admin