apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  labels:
    app: {{ .Values.labelapp }}
    group: {{ .Values.group }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        group: {{ .Values.group }}
    spec:
      containers:
        - name: {{ .Values.app.name }}-container
          image: {{ .Values.app.container.image }}  
          ports:
            - containerPort: {{ .Values.app.container.port }}
          {{- if .Values.app.config }}
          envFrom:
            - configMapRef:
                name: {{ .Values.app.config.name }}
          {{- end }}
          {{- if .Values.app.secret }}
          env:
          {{- $secretName := .Values.app.secret.name }}
          {{- range .Values.app.secret.data }}
            - name: {{ .key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ .key }}
          {{- end}}
          {{- end}}