apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  labels:
    app: {{ .Values.labelapp }}
    group: {{ .Values.group }}
spec:
  type: {{ .Values.app.service.type }}
  selector:             
    app: {{ .Values.app.name }}
  ports:
    - protocol: {{ .Values.app.service.protocol }}
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.container.port }}   