apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - inventory-app-namespace.yaml
  - inventory-api/inventory-api-deployment.yaml
  - inventory-api/inventory-api-service.yaml
  - inventory-api/inventory-api-ingress.yaml
  - inventory-ui/inventory-ui-deployment.yaml
  - inventory-ui/inventory-ui-service.yaml
  - inventory-ui/inventory-ui-ingress.yaml
  - inventory-db/postgres-config.yaml
  - inventory-db/postgres-secret.yaml
  - inventory-db/inventory-db-storage.yaml
  - inventory-db/inventory-db-deployment.yaml
  - inventory-db/inventory-db-service.yaml