{{- if .Values.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.genericApp.name }}-ingress
  labels:
    app: {{ .Values.labelapp }}
    group: {{ .Values.group }}
  {{- if .Values.genericApp.ingress.annotations }}
  annotations:
  {{- range .Values.genericApp.ingress.annotations }}
    {{ .key }}: {{ .value | quote }}
  {{- end }}
  {{- end }}
spec:
  rules:
  {{- range .Values.genericApp.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ .backend.serviceName }}
              servicePort: {{ .backend.servicePort }}
        {{- end }}
  {{- end }}
{{- end }}
