app: inventory-app
group: db

postgres:
  name: inventory-db
  
  config:
    name: postgres-config
    data:
      - key: POSTGRES_DB
        value: inventory
      - key: POSTGRES_USER
        value: postgresadmin
      - key: POSTGRES_PORT
        value: "5433"
      - key: POSTGRES_HOST
        value: inventory-db-service
  
  volume:
    pv:
      hostPath: "/opt/postgres/helm-data"
  
  secret:
    name: postgres-secret
    data:
      - key: POSTGRES_PASSWORD
        value: YWRtaW4xMjMK
  
  service:
    port: 5433
    
