apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: inventory-app
  labels:
    app: postgres
data:
  POSTGRES_DB: inventory
  POSTGRES_USER: postgresadmin
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: inventory-db-service