apiVersion: v1
kind: Service
metadata:
  name: prometheus-np-service
  namespace: istio-system
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      nodePort: 30909
  selector:
    app: prometheus
