# volume claim for backend DB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbclaim
  namespace: simpleapp-reactapp
  labels:
    db: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage

---
# volume for backend DB
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
  namespace: simpleapp-reactapp
  labels:
    db: mongo
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mongodata"
    type: DirectoryOrCreate

---
# Cluster IP for backend
apiVersion: v1
kind: Service
metadata:
  name: mongo-cluster
  namespace: simpleapp-reactapp
  labels:
    db: mongo
spec:
  selector:
    db: mongo
  ports:
    - port: 27017
      targetPort: 27017

---
# Deployment for backend DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-db
  namespace: simpleapp-reactapp
  labels:
    db: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mongo
  template:
    metadata:
      name: db-pods
      namespace: simpleapp-reactapp
      labels:
        db: mongo
    spec:
      containers:
      - name: db-containers
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: root
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: dbclaim