apiVersion: v1
kind: Service
metadata:
  name: inventory-api-lb
  namespace: inventory-app
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 5000
  selector:
    app: inventory-api