apiVersion: v1
kind: Service
metadata:
  name: inventory-db-service
  namespace: inventory-app
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30001
  selector:
    app: postgres