apiVersion: v2
name: inventory-app-chart
description: A Helm chart for Kubernetes for the Inventory-App

type: application

version: 0.2

appVersion: 0.1

dependencies:
  - name: inventoryDB
    condition: enabled
  - name: inventoryAPI
    condition: enabled
  - name: inventoryUI
    condition: enabled

home: https://github.com/FunkeMT/nl.vu.containerization
maintainers:
  - name: Markus Funke
    url: https://github.com/FunkeMT
